#!/usr/bin/env python

# Super cheesy decoding of JWT tokens for debugging

import base64
import sys

if len(sys.argv) > 1:
    token = sys.argv[1]
else:
    token = sys.stdin.read()

print
for part in token.split('.'):
    for pad in ['', '=', '==']:
        try:
            d = base64.b64decode(part + pad)
            if d.startswith('{'):
                print d
            else:
                print 'Binary bits'
        except TypeError:
            pass
        else:
            break
    print
