#!/bin/sh

# This implements a docker credential store as documented at
# https://docs.docker.com/engine/reference/commandline/login/

case "$1" in
    "store")
        echo "Store not supported" >&2
        exit 1
        ;;
    "get")
        data=$(curl -s --user demouser:demopass https://localhost:8080/getpassword)
        username=$(echo "$data" | jq -r .username)
        password=$(echo "$data" | jq -r .password)
        echo "{\"Username\":\"$username\",\"Secret\":\"$password\"}"
        ;;
    "erase")
        echo "Erase not supported" >&2
        exit 1
        ;;
    *)
        echo "Unrecognized operation '$1'" >&2
        exit 1
        ;;
esac
